baseURL = "/"
languageCode = "en-us"
title = "Seattle Wren"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  censusApiKey = "59718e1cb53e0c767125daecc83e2d6dccd77d64"

[taxonomies]
  category = "categories"
  tag = "tags"
